### ISSUE TITLE
Any idea on how to make it 4d (or nd)?

### ISSUE THREAD

**Issue by clementpoiret** [msseibel/EquivariantNetworks#1]
Hi,

I'm interested in using gauge equivariant networks on fMRI, which are 4D volumes. Do you think that this is possible to do?

Thanks,
Clément.

**Comment by msseibel** [comment]
Hi Clément,

Unfortunately I have not checked issues for this repository.

I used this implementation only for 2D images obtained by slicing 3D CT Volumes.  Extending the idea to higher dimensions (even) 3D seems not easy. Max Welling has some good talks about it on YouTube. Right now I only find [this](https://www.youtube.com/watch?v=Wx8J-Kw3fTA&ab_channel=InstituteforAdvancedStudy) talk about equivariance for Graph Nets. He also touches on the problems of defining equivariance in higher dimensions.
